new_aldvmm <- function(fit,
                       cov,
                       y,
                       mm,
                       ncmp,
                       gof,
                       pred,
                       pred.se = NULL,
                       init,
                       call,
                       formula,
                       terms,
                       data,
                       psi,
                       dist,
                       lcoef,
                       lcpar,
                       lcmp,
                       optim.method,
                       init.method,
                       level,
                       na.action) {
  
  outlist <- list(coef    = fit[["par"]],
                  se      = cov[["se"]],
                  z       = cov[["z"]],
                  p       = cov[["p"]],
                  lower   = cov[["lower"]],
                  upper   = cov[["upper"]],
                  hessian = cov[["hessian"]],
                  cov     = cov[["cv"]],
                  n       = length(y),
                  k       = lapply(mm, function (x) ncol(x)),
                  ncmp    = ncmp,
                  df.null = lapply(terms, function (x) {
                    length(y) - as.integer(attr(x, "intercept") > 0L)
                  }),
                  df.residual = lapply(lapply(mm, function (x) ncol(x)), {
                    function (x) length(y) - x - 1
                  }),
                  gof     = list(ll      = gof[["ll"]],
                                 deviance = gof[["deviance"]],
                                 aic     = gof[["aic"]],
                                 bic     = gof[["bic"]],
                                 mse     = gof[["mse"]],
                                 mae     = gof[["mae"]]),
                  pred    = list(y = pred[["y"]],
                                 yhat = pred[["yhat"]],
                                 res = pred[["res"]],
                                 se.fit = pred.se[["se.fit"]],
                                 lower.fit = pred.se[["lower.fit"]],
                                 upper.fit = pred.se[["upper.fit"]],
                                 prob = pred[["prob"]]),
                  init    = init,
                  call    = call,
                  formula = formula,
                  terms   = terms,
                  contrasts = lapply(mm, function (x) attr(x, "contrasts")),
                  data    = data,
                  psi     = psi,
                  dist    = dist,
                  label   = list("lcoef" = lcoef, 
                                 "lcpar" = lcpar,
                                 "lcmp" = lcmp,
                                 "lvar" = lapply(mm, function(x) colnames(x))),
                  optim.method = optim.method,
                  init.method = init.method,
                  level   = level,
                  na.action = na.action)
  
  structure(outlist, class = "aldvmm")
  
}